### ISSUE TITLE
Player stays in scoreboard when they disconnect and when you click on it causes a lua error.

### ISSUE THREAD

**Issue by Synkstar** [ZionDevelopers/sui-scoreboard#14]
[ERROR] lua/sui_scoreboard/client/player_row.lua:346: Tried to use a NULL entity!
  1. Team - [C]:-1
   2. unknown - lua/sui_scoreboard/client/player_row.lua:346
    3. sort - [C]:-1
     4. unknown - lua/sui_scoreboard/client/scoreboard.lua:178

**Comment by juliocoliveira** [comment]
I guess it does not happen everytime a player disconnect or I would receive a lot of more issues.
I cannot reproduce it, so cannot fix it, i checked on this line and there is no more this code, maybe got fixed already.
Sorry for the delay I was not getting notifications.

**Comment by Synkstar** [comment]
Its ok I kind of forgot that I made this.....
