### ISSUE TITLE
Time resets when server restarts

### ISSUE THREAD

**Issue by Weldeasy** [ZionDevelopers/sui-scoreboard#15]
So when the server crashes or is restarted, all the TIME info and the stats are GONE.

**Comment by juliocoliveira** [comment]
The time its normal, its Time since the connection, But the stats should not go away.
But you are the first with this issue, should be a issue the the SRCDS wiping the server.db or something.
I cannot reproduce this.

**Comment by juliocoliveira** [comment]
The time probably because you don't have utime, But the stats should not go away.
But you are the first with this issue, should be a issue the the SRCDS wiping the server.db or something.
I cannot reproduce this.
