### ISSUE TITLE
Total time spent clears when server is restarted

### ISSUE THREAD

**Issue by BlackIceKB** [ZionDevelopers/sui-scoreboard#24]
Hello,

Not sure if I am missing something obvious, but the total time a player is tracked on the server is reset when the server is shut down or restarted, e.g. to apply new addons. I have not seen this on other servers that experience shut downs, restarts and crashes, hence me not being sure if I've missed something.

I've tested it by joining my server earlier today, and rejoining later. It does add it up from that previous session, but I have not restarted it since that early session, but it does reset when I restart the server.

**Comment by juliocoliveira** [comment]
Make sure you have uTime installed.

**Comment by juliocoliveira** [comment]
Make sure you have uTime installed if you are using ULX. https://github.com/TeamUlysses/utime

**Comment by BlackIceKB** [comment]
Cheers, it was a bit confusing as I didn't see it on the workshop originally. Should be good now!
