### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jimmyking2004** [ZionDevelopers/sui-scoreboard#29]
I'm running a server with mercury installed and with the scoreboard in addons, I press the tab button while on the server I still get the default scoreboard is there something I have to enable?

**Comment by juliocoliveira** [comment]
I'm afraid I cannot help you there.
IF there is something you need to enable inside Mercury to load the scoreboard I don't know.
I tested here and indeed by default it does not load.
The mercury support was added as a contribution, So I didn't coded or tested or used myself.

Anyway, this project is abandoned, Is over 7 years without add updates and you should not use it.
I don't know if the error I got about steamid bans from mercury is responsible to not load the scoreboard. 

I recommend you to switch over ULX, there the scoreboard is working fine.

**Comment by juliocoliveira** [comment]
OK, said that, I got a free time and took the time to learn a bit about mercury and implemented a fix to load the scoreboard if mercury is loaded, test it and report please.

**Comment by jimmyking2004** [comment]
it works but there are a few problems
![image_2024-05-19_195316241](https://github.com/ZionDevelopers/sui-scoreboard/assets/47538595/0660d67f-647d-4e98-99e5-86bdd08dec2a)


and i also can kick myself and supposably ban myself too despite looking like the buttons are greyed out unless that's normal
![image_2024-05-19_194849102](https://github.com/ZionDevelopers/sui-scoreboard/assets/47538595/ceeb451a-18d3-4049-b842-338ac35404db)

**Comment by juliocoliveira** [comment]
The error was fixed, but the buttons being able to kick yourself, I really don't see the issue.

**Comment by jimmyking2004** [comment]
appears to be working without any errors thank you

i also thought the buttons was an issue but i guess not
