### ISSUE TITLE
3 Missing Icon. Discord, Steam workshop and logo

### ISSUE THREAD

**Issue by Pingu1239** [ZionDevelopers/sui-scoreboard#31]
Hello, i already add 3 icon (steam workshop, logo and discord) to sui scoreboard but in multiplayer not work and singleplayer is work.

https://github.com/user-attachments/assets/47c435c7-66a8-47a0-8d41-6ac9f8ee3579 <<< This is multiplayer

![Screenshot 2024-10-17 200354](https://github.com/user-attachments/assets/ad1b8073-79bb-4dbe-8f17-ddf147c30f8f)

![Screenshot 2024-10-17 200409](https://github.com/user-attachments/assets/f875f30f-3954-47e8-9b1c-0aca5584d4a6)

**Comment by juliocoliveira** [comment]
This issue tracker, is for issues with this current modification with my addon, not to help you with your current modification.

Still I'll help you only this time.

You need force client to download the resource.
Use the lua function resource.AddFile: <https://wiki.facepunch.com/gmod/resource.AddFile>
And then use resource.AddWorkshop: <https://wiki.facepunch.com/gmod/resource.AddWorkshop> if you are hosting it on steam workshop.

**Comment by juliocoliveira** [comment]
Put in here: https://github.com/ZionDevelopers/sui-scoreboard/blob/8c9c110971217d54ddfbe04a9ee646dcc5c78955/lua/autorun/_sui_scoreboard.lua#L49

**Comment by Pingu1239** [comment]
Thank you so much! Now scoreboard is **working!**

https://github.com/user-attachments/assets/2f82e1ad-3237-4741-a776-5cb3f4c218d2
