### ISSUE TITLE
Compatibility with Vermillion 2?

### ISSUE THREAD

**Issue by SteelShot** [ZionDevelopers/sui-scoreboard#7]
Basically its a new growing addon, getting quite popular now, it would be really nice to the SUI scoreboard to be compatible with it. The developer told me to tell you to use the github version of his addon, not the workshop one, as he changed a lot of core things. His post: http://i.imgur.com/3llInyS.png

Addons Page: http://steamcommunity.com/sharedfiles/filedetails/?id=338063408&tscn=1434966524
Thats the addons github: https://github.com/nedhyett/Vermilion

**Comment by juliocoliveira** [comment]
I'll think about that, But if you want you are free to collaborate to this project

**Comment by SteelShot** [comment]
Ha, I forgot that i made this suggestion xD
Im not sure on the state of the addon, it seems to be still maintained, and myself I have stopped playing or hosting GM servers.
